- hosts: localhost
  vars:
    source_key: "./ssh/.ssh/github"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Set global SSH configuration file
    ansible.builtin.set_fact:
      ansible_ssh_common_args: "-F ./ssh/.ssh/config"

  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/git-setup.yml
    - include: tasks/core-setup.yml
    - include: tasks/install-zsh.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/dotfiles.yml
